### ISSUE TITLE
Installation breaks due to a missing python package NEAT

### ISSUE THREAD

**Issue by jsferreira** [rogeriojorge/NEAT#1]
This issue rises when running `python setup.py build`. 

``` python setup.py build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from skbuild import setup
ModuleNotFoundError: No module named 'skbuild'
```

The solution is to advise to install the python package scikit-build.

**Comment by jsferreira** [comment]
Following the previous issue, there is the need to also install another package due to:
```python
'/Users/jorgeferreira/opt/anaconda3/bin/python3' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'
```
So pybind11 is also needed. Probably you should add a requirements.txt file with the list of packages to install first before installing/compiling.

**Comment by jsferreira** [comment]
I would add also the proper command line to install the requirements for completeness.
Eg.
`pip install -r requirements.txt [--user]`

**Comment by rogeriojorge** [comment]
Added the command. Thank you @jsferreira
